// automatically generated by the FlatBuffers compiler, do not modify

package OpenTraffic;

public final class VehicleType {
  private VehicleType() { }
  public static final byte Auto = 0;

  public static final String[] names = { "Auto", };

  public static String name(int e) { return names[e]; }
}

